### ISSUE TITLE
Timeline: images distorted in Chrome/macOS, fix included

### ISSUE THREAD

**Issue by glueckpress** [microdotblog/issues#26]
Currently this gets applied to images in the timeline on https://micro.blog/:

```css
img {
	max-width: 100%;
	max-height: 500px;
}
```

This results in a distorted presentation in Chrome/macOS:

<img width="658" alt="screen shot 2017-05-01 at 12 11 00" src="https://cloud.githubusercontent.com/assets/308422/25577580/601f56c4-2e67-11e7-95b7-3eacca9762cb.png">

Setting `width` to `auto` appears to solve the issue:

```css
img {
	max-width: 100%;
	max-height: 500px;
	width: auto;
	height: auto;
}
```

<img width="649" alt="screen shot 2017-05-01 at 12 14 15" src="https://cloud.githubusercontent.com/assets/308422/25577615/bdaad6b0-2e67-11e7-8ce3-af912a7ffa57.png">
